<?php

namespace ContainerZYHxHcm;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LCbobIMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LCbobIM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LCbobIM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'inscripcionFinal' => ['privates', '.errored..service_locator.LCbobIM.App\\Entity\\InscripcionFinal', NULL, 'Cannot autowire service ".service_locator.LCbobIM": it references class "App\\Entity\\InscripcionFinal" but no such service exists.'],
            'inscripcionFinalRepository' => ['privates', 'App\\Repository\\InscripcionFinalRepository', 'getInscripcionFinalRepositoryService', true],
        ], [
            'inscripcionFinal' => 'App\\Entity\\InscripcionFinal',
            'inscripcionFinalRepository' => 'App\\Repository\\InscripcionFinalRepository',
        ]);
    }
}
