<?php

namespace ContainerZYHxHcm;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__QxwYmsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..qxwYms' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..qxwYms'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'notaRepository' => ['privates', 'App\\Repository\\NotaRepository', 'getNotaRepositoryService', true],
            'notum' => ['privates', '.errored..service_locator..qxwYms.App\\Entity\\Nota', NULL, 'Cannot autowire service ".service_locator..qxwYms": it references class "App\\Entity\\Nota" but no such service exists.'],
        ], [
            'notaRepository' => 'App\\Repository\\NotaRepository',
            'notum' => 'App\\Entity\\Nota',
        ]);
    }
}
