<?php

namespace ContainerRD2a786;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_V8mJv2fService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.V8mJv2f' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.V8mJv2f'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'examenFinal' => ['privates', '.errored..service_locator.V8mJv2f.App\\Entity\\ExamenFinal', NULL, 'Cannot autowire service ".service_locator.V8mJv2f": it references class "App\\Entity\\ExamenFinal" but no such service exists.'],
            'examenFinalRepository' => ['privates', 'App\\Repository\\ExamenFinalRepository', 'getExamenFinalRepositoryService', true],
        ], [
            'examenFinal' => 'App\\Entity\\ExamenFinal',
            'examenFinalRepository' => 'App\\Repository\\ExamenFinalRepository',
        ]);
    }
}
