<?php

namespace ContainerRD2a786;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VdX9ZX0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VdX9ZX0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VdX9ZX0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'inscripcionFinalRepository' => ['privates', 'App\\Repository\\InscripcionFinalRepository', 'getInscripcionFinalRepositoryService', true],
        ], [
            'inscripcionFinalRepository' => 'App\\Repository\\InscripcionFinalRepository',
        ]);
    }
}
