<?php

namespace ContainerRD2a786;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_R06nQXiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.r06nQXi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.r06nQXi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'examenAlumno' => ['privates', '.errored..service_locator.r06nQXi.App\\Entity\\ExamenAlumno', NULL, 'Cannot autowire service ".service_locator.r06nQXi": it references class "App\\Entity\\ExamenAlumno" but no such service exists.'],
            'examenAlumnoRepository' => ['privates', 'App\\Repository\\ExamenAlumnoRepository', 'getExamenAlumnoRepositoryService', true],
        ], [
            'examenAlumno' => 'App\\Entity\\ExamenAlumno',
            'examenAlumnoRepository' => 'App\\Repository\\ExamenAlumnoRepository',
        ]);
    }
}
