<?php

namespace ContainerX3aa9O3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YzhKFlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yzhKFl_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yzhKFl_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'calendarioClase' => ['privates', '.errored..service_locator.yzhKFl_.App\\Entity\\CalendarioClase', NULL, 'Cannot autowire service ".service_locator.yzhKFl_": it references class "App\\Entity\\CalendarioClase" but no such service exists.'],
        ], [
            'calendarioClase' => 'App\\Entity\\CalendarioClase',
        ]);
    }
}
