<?php

namespace ContainerFWkAeBv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RbCKgcTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rbCKgcT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rbCKgcT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cursada' => ['privates', '.errored..service_locator.rbCKgcT.App\\Entity\\Cursada', NULL, 'Cannot autowire service ".service_locator.rbCKgcT": it references class "App\\Entity\\Cursada" but no such service exists.'],
            'cursadaRepository' => ['privates', 'App\\Repository\\CursadaRepository', 'getCursadaRepositoryService', true],
        ], [
            'cursada' => 'App\\Entity\\Cursada',
            'cursadaRepository' => 'App\\Repository\\CursadaRepository',
        ]);
    }
}
