<?php

namespace ContainerFWkAeBv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1Qpv22Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1_Qpv22' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1_Qpv22'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'instituto' => ['privates', '.errored..service_locator.1_Qpv22.App\\Entity\\Instituto', NULL, 'Cannot autowire service ".service_locator.1_Qpv22": it references class "App\\Entity\\Instituto" but no such service exists.'],
        ], [
            'instituto' => 'App\\Entity\\Instituto',
        ]);
    }
}
