<?php

namespace ContainerFWkAeBv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ij9q400Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ij9q400' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ij9q400'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'asignaturaRepository' => ['privates', 'App\\Repository\\AsignaturaRepository', 'getAsignaturaRepositoryService', true],
            'comisionRepository' => ['privates', 'App\\Repository\\ComisionRepository', 'getComisionRepositoryService', true],
            'cursadaDocenteRepository' => ['privates', 'App\\Repository\\CursadaDocenteRepository', 'getCursadaDocenteRepositoryService', true],
            'cursadaRepository' => ['privates', 'App\\Repository\\CursadaRepository', 'getCursadaRepositoryService', true],
            'cursoRepository' => ['privates', 'App\\Repository\\CursoRepository', 'getCursoRepositoryService', true],
            'tecnicaturaRepository' => ['privates', 'App\\Repository\\TecnicaturaRepository', 'getTecnicaturaRepositoryService', true],
        ], [
            'asignaturaRepository' => 'App\\Repository\\AsignaturaRepository',
            'comisionRepository' => 'App\\Repository\\ComisionRepository',
            'cursadaDocenteRepository' => 'App\\Repository\\CursadaDocenteRepository',
            'cursadaRepository' => 'App\\Repository\\CursadaRepository',
            'cursoRepository' => 'App\\Repository\\CursoRepository',
            'tecnicaturaRepository' => 'App\\Repository\\TecnicaturaRepository',
        ]);
    }
}
