<?php

namespace ContainerVxFxMKO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAsistenciaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.uqsmDdT.App\Entity\Asistencia' shared service.
     *
     * @return \App\Entity\Asistencia
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.uqsmDdT": it references class "App\\Entity\\Asistencia" but no such service exists.');
    }
}
