<?php

namespace ContainerVxFxMKO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCalendarioClase2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.yzhKFl_.App\Entity\CalendarioClase' shared service.
     *
     * @return \App\Entity\CalendarioClase
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.yzhKFl_": it references class "App\\Entity\\CalendarioClase" but no such service exists.');
    }
}
