<?php

namespace ContainerXyETw9i;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XaXwVTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xa_XwVT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xa_XwVT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'horario' => ['privates', '.errored..service_locator.xa_XwVT.App\\Entity\\Horario', NULL, 'Cannot autowire service ".service_locator.xa_XwVT": it references class "App\\Entity\\Horario" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'horario' => 'App\\Entity\\Horario',
        ]);
    }
}
