<?php

namespace ContainerXyETw9i;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PTCYBLkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pTCYBLk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pTCYBLk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'inscripcionFinal' => ['privates', '.errored..service_locator.pTCYBLk.App\\Entity\\InscripcionFinal', NULL, 'Cannot autowire service ".service_locator.pTCYBLk": it references class "App\\Entity\\InscripcionFinal" but no such service exists.'],
        ], [
            'inscripcionFinal' => 'App\\Entity\\InscripcionFinal',
        ]);
    }
}
