<?php

namespace ContainerYAccG0f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7AwcF1WService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7AwcF1W' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7AwcF1W'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'asignaturaRepository' => ['privates', 'App\\Repository\\AsignaturaRepository', 'getAsignaturaRepositoryService', true],
            'tecnicaturaRepository' => ['privates', 'App\\Repository\\TecnicaturaRepository', 'getTecnicaturaRepositoryService', true],
        ], [
            'asignaturaRepository' => 'App\\Repository\\AsignaturaRepository',
            'tecnicaturaRepository' => 'App\\Repository\\TecnicaturaRepository',
        ]);
    }
}
