<?php

namespace ContainerYAccG0f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LHmEKYyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lHmEKYy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lHmEKYy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entity' => ['privates', '.errored..service_locator.lHmEKYy.App\\Entity\\ExamenFinal', NULL, 'Cannot autowire service ".service_locator.lHmEKYy": it references class "App\\Entity\\ExamenFinal" but no such service exists.'],
        ], [
            'entity' => 'App\\Entity\\ExamenFinal',
        ]);
    }
}
