<?php

namespace ContainerLxcwixx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Q4bsI0SService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.q4bsI0S' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.q4bsI0S'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'region' => ['privates', '.errored..service_locator.q4bsI0S.App\\Entity\\Region', NULL, 'Cannot autowire service ".service_locator.q4bsI0S": it references class "App\\Entity\\Region" but no such service exists.'],
        ], [
            'region' => 'App\\Entity\\Region',
        ]);
    }
}
