<?php

namespace ContainerLxcwixx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHorario2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.bIPZ3W7.App\Entity\Horario' shared service.
     *
     * @return \App\Entity\Horario
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.bIPZ3W7": it references class "App\\Entity\\Horario" but no such service exists.');
    }
}
