<?php

namespace ContainerLxcwixx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInscripcionFinal2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.yvYK5Bh.App\Entity\InscripcionFinal' shared service.
     *
     * @return \App\Entity\InscripcionFinal
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.yvYK5Bh": it references class "App\\Entity\\InscripcionFinal" but no such service exists.');
    }
}
