<?php

namespace ContainerVSIEiwB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WqSOxPAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wqSOxPA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wqSOxPA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'asistencium' => ['privates', '.errored..service_locator.wqSOxPA.App\\Entity\\Asistencia', NULL, 'Cannot autowire service ".service_locator.wqSOxPA": it references class "App\\Entity\\Asistencia" but no such service exists.'],
        ], [
            'asistencium' => 'App\\Entity\\Asistencia',
        ]);
    }
}
