<?php

namespace ContainerVSIEiwB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PHazE3FService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pHazE3F' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pHazE3F'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'rolRepository' => ['privates', 'App\\Repository\\RolRepository', 'getRolRepositoryService', true],
        ], [
            'rolRepository' => 'App\\Repository\\RolRepository',
        ]);
    }
}
