<?php

namespace ContainerVSIEiwB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRol2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.oHNzwhY.App\Entity\Rol' shared service.
     *
     * @return \App\Entity\Rol
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.oHNzwhY": it references class "App\\Entity\\Rol" but no such service exists.');
    }
}
