<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Nota extends \App\Entity\Nota implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Nota' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Nota' . "\0" . 'parcial', '' . "\0" . 'App\\Entity\\Nota' . "\0" . 'recuperatorio1', '' . "\0" . 'App\\Entity\\Nota' . "\0" . 'parcial2', '' . "\0" . 'App\\Entity\\Nota' . "\0" . 'recuperatorio2'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Nota' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Nota' . "\0" . 'parcial', '' . "\0" . 'App\\Entity\\Nota' . "\0" . 'recuperatorio1', '' . "\0" . 'App\\Entity\\Nota' . "\0" . 'parcial2', '' . "\0" . 'App\\Entity\\Nota' . "\0" . 'recuperatorio2'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Nota $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getParcial(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParcial', []);

        return parent::getParcial();
    }

    /**
     * {@inheritDoc}
     */
    public function setParcial(?string $parcial): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParcial', [$parcial]);

        return parent::setParcial($parcial);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecuperatorio1(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecuperatorio1', []);

        return parent::getRecuperatorio1();
    }

    /**
     * {@inheritDoc}
     */
    public function setRecuperatorio1(?string $recuperatorio1): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecuperatorio1', [$recuperatorio1]);

        return parent::setRecuperatorio1($recuperatorio1);
    }

    /**
     * {@inheritDoc}
     */
    public function getParcial2(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParcial2', []);

        return parent::getParcial2();
    }

    /**
     * {@inheritDoc}
     */
    public function setParcial2(?string $parcial2): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParcial2', [$parcial2]);

        return parent::setParcial2($parcial2);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecuperatorio2(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecuperatorio2', []);

        return parent::getRecuperatorio2();
    }

    /**
     * {@inheritDoc}
     */
    public function setRecuperatorio2(?string $recuperatorio2): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecuperatorio2', [$recuperatorio2]);

        return parent::setRecuperatorio2($recuperatorio2);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
