<?php

namespace ContainerZNjCbGv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FEhGlnPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FEhGlnP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FEhGlnP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'notum' => ['privates', '.errored..service_locator.FEhGlnP.App\\Entity\\Nota', NULL, 'Cannot autowire service ".service_locator.FEhGlnP": it references class "App\\Entity\\Nota" but no such service exists.'],
        ], [
            'notum' => 'App\\Entity\\Nota',
        ]);
    }
}
