<?php

namespace ContainerZNjCbGv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RfLyIy6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RfLyIy6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RfLyIy6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'horario' => ['privates', '.errored..service_locator.RfLyIy6.App\\Entity\\Horario', NULL, 'Cannot autowire service ".service_locator.RfLyIy6": it references class "App\\Entity\\Horario" but no such service exists.'],
        ], [
            'em' => '?',
            'horario' => 'App\\Entity\\Horario',
        ]);
    }
}
