<?php

namespace ContainerZNjCbGv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EnkBk2JService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EnkBk2J' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EnkBk2J'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'alumnoRepository' => ['privates', 'App\\Repository\\AlumnoRepository', 'getAlumnoRepositoryService', true],
            'carrerasRepository' => ['privates', 'App\\Repository\\CarrerasRepository', 'getCarrerasRepositoryService', true],
            'cursadaRepository' => ['privates', 'App\\Repository\\CursadaRepository', 'getCursadaRepositoryService', true],
            'cursoRepository' => ['privates', 'App\\Repository\\CursoRepository', 'getCursoRepositoryService', true],
        ], [
            'alumnoRepository' => 'App\\Repository\\AlumnoRepository',
            'carrerasRepository' => 'App\\Repository\\CarrerasRepository',
            'cursadaRepository' => 'App\\Repository\\CursadaRepository',
            'cursoRepository' => 'App\\Repository\\CursoRepository',
        ]);
    }
}
