<?php

<<<<<<< HEAD:var/cache/dev/Container8Un2Ui4/get_ServiceLocator_S6cVw0tService.php
namespace Container8Un2Ui4;
=======
<<<<<<<< HEAD:var/cache/dev/ContainerZedAest/get_ServiceLocator_S6cVw0tService.php
namespace ContainerZedAest;

========
namespace ContainerWxp6ynK;
>>>>>>>> 15004e1e441728d7bfb90a33f34e34e28484990f:var/cache/dev/ContainerWxp6ynK/get_ServiceLocator_ABnFrU4Service.php
>>>>>>> 9ff131dc3f1d539d565d1ea1bbe799cf5823e506:var/cache/dev/ContainerWxp6ynK/get_ServiceLocator_ABnFrU4Service.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_S6cVw0tService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.S6cVw0t' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.S6cVw0t'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'persona' => ['privates', '.errored..service_locator.S6cVw0t.App\\Entity\\Persona', NULL, 'Cannot autowire service ".service_locator.S6cVw0t": it references class "App\\Entity\\Persona" but no such service exists.'],
            'personaRepository' => ['privates', 'App\\Repository\\PersonaRepository', 'getPersonaRepositoryService', true],
        ], [
            'persona' => 'App\\Entity\\Persona',
            'personaRepository' => 'App\\Repository\\PersonaRepository',
        ]);
    }
}
