<?php

<<<<<<< HEAD:var/cache/dev/Container8Un2Ui4/get_ServiceLocator_GlfVhgCService.php
namespace Container8Un2Ui4;
=======
<<<<<<<< HEAD:var/cache/dev/ContainerZedAest/get_ServiceLocator_GlfVhgCService.php
namespace ContainerZedAest;

========
namespace ContainerWxp6ynK;
>>>>>>>> 15004e1e441728d7bfb90a33f34e34e28484990f:var/cache/dev/ContainerWxp6ynK/get_ServiceLocator_CRURelYService.php
>>>>>>> 9ff131dc3f1d539d565d1ea1bbe799cf5823e506:var/cache/dev/ContainerWxp6ynK/get_ServiceLocator_CRURelYService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GlfVhgCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GlfVhgC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GlfVhgC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'turno' => ['privates', '.errored..service_locator.GlfVhgC.App\\Entity\\Turno', NULL, 'Cannot autowire service ".service_locator.GlfVhgC": it references class "App\\Entity\\Turno" but no such service exists.'],
            'turnoRepository' => ['privates', 'App\\Repository\\TurnoRepository', 'getTurnoRepositoryService', true],
        ], [
            'turno' => 'App\\Entity\\Turno',
            'turnoRepository' => 'App\\Repository\\TurnoRepository',
        ]);
    }
}
