<?php

<<<<<<< HEAD:var/cache/dev/Container8Un2Ui4/get_ServiceLocator_Lj6XXojService.php
namespace Container8Un2Ui4;
=======
<<<<<<<< HEAD:var/cache/dev/ContainerZedAest/get_ServiceLocator_Lj6XXojService.php
namespace ContainerZedAest;

========
namespace ContainerWxp6ynK;
>>>>>>>> 15004e1e441728d7bfb90a33f34e34e28484990f:var/cache/dev/ContainerWxp6ynK/get_ServiceLocator_ZckD2vCService.php
>>>>>>> 9ff131dc3f1d539d565d1ea1bbe799cf5823e506:var/cache/dev/ContainerWxp6ynK/get_ServiceLocator_ZckD2vCService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Lj6XXojService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lj6XXoj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lj6XXoj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'carrera' => ['privates', '.errored..service_locator.lj6XXoj.App\\Entity\\Carreras', NULL, 'Cannot autowire service ".service_locator.lj6XXoj": it references class "App\\Entity\\Carreras" but no such service exists.'],
        ], [
            'carrera' => 'App\\Entity\\Carreras',
        ]);
    }
}
