<?php

namespace Container8Un2Ui4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WqXBDHDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wqXBDHD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wqXBDHD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'curso' => ['privates', '.errored..service_locator.wqXBDHD.App\\Entity\\Curso', NULL, 'Cannot autowire service ".service_locator.wqXBDHD": it references class "App\\Entity\\Curso" but no such service exists.'],
        ], [
            'curso' => 'App\\Entity\\Curso',
        ]);
    }
}
