<?php

<<<<<<< HEAD:var/cache/dev/Container8Un2Ui4/get_ServiceLocator_8lLQrxiService.php
namespace Container8Un2Ui4;
=======
<<<<<<<< HEAD:var/cache/dev/ContainerZedAest/get_ServiceLocator_V8mJv2fService.php
namespace ContainerZedAest;

========
namespace ContainerWxp6ynK;
>>>>>>>> 15004e1e441728d7bfb90a33f34e34e28484990f:var/cache/dev/ContainerWxp6ynK/get_ServiceLocator_U2fciABService.php
>>>>>>> 9ff131dc3f1d539d565d1ea1bbe799cf5823e506:var/cache/dev/ContainerWxp6ynK/get_ServiceLocator_U2fciABService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
<<<<<<< HEAD:var/cache/dev/Container8Un2Ui4/get_ServiceLocator_8lLQrxiService.php
class get_ServiceLocator_8lLQrxiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8lLQrxi' shared service.
=======
class get_ServiceLocator_V8mJv2fService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.V8mJv2f' shared service.
>>>>>>> 9ff131dc3f1d539d565d1ea1bbe799cf5823e506:var/cache/dev/ContainerWxp6ynK/get_ServiceLocator_U2fciABService.php
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
<<<<<<< HEAD:var/cache/dev/Container8Un2Ui4/get_ServiceLocator_8lLQrxiService.php
        return $container->privates['.service_locator.8lLQrxi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'examenAlumnoRepository' => ['privates', 'App\\Repository\\ExamenAlumnoRepository', 'getExamenAlumnoRepositoryService', true],
            'examenFinal' => ['privates', '.errored..service_locator.8lLQrxi.App\\Entity\\ExamenFinal', NULL, 'Cannot autowire service ".service_locator.8lLQrxi": it references class "App\\Entity\\ExamenFinal" but no such service exists.'],
=======
        return $container->privates['.service_locator.V8mJv2f'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'examenFinal' => ['privates', '.errored..service_locator.V8mJv2f.App\\Entity\\ExamenFinal', NULL, 'Cannot autowire service ".service_locator.V8mJv2f": it references class "App\\Entity\\ExamenFinal" but no such service exists.'],
>>>>>>> 9ff131dc3f1d539d565d1ea1bbe799cf5823e506:var/cache/dev/ContainerWxp6ynK/get_ServiceLocator_U2fciABService.php
            'examenFinalRepository' => ['privates', 'App\\Repository\\ExamenFinalRepository', 'getExamenFinalRepositoryService', true],
        ], [
            'examenAlumnoRepository' => 'App\\Repository\\ExamenAlumnoRepository',
            'examenFinal' => 'App\\Entity\\ExamenFinal',
            'examenFinalRepository' => 'App\\Repository\\ExamenFinalRepository',
        ]);
    }
}
