<?php

<<<<<<< HEAD:var/cache/dev/Container8Un2Ui4/get_ServiceLocator_M1q10pkService.php
namespace Container8Un2Ui4;
=======
<<<<<<<< HEAD:var/cache/dev/ContainerZedAest/get_ServiceLocator_M1q10pkService.php
namespace ContainerZedAest;

========
namespace ContainerWxp6ynK;
>>>>>>>> 15004e1e441728d7bfb90a33f34e34e28484990f:var/cache/dev/ContainerWxp6ynK/get_ServiceLocator_Q4LbOCZService.php
>>>>>>> 9ff131dc3f1d539d565d1ea1bbe799cf5823e506:var/cache/dev/ContainerWxp6ynK/get_ServiceLocator_Q4LbOCZService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_M1q10pkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.M1q10pk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.M1q10pk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'alumnoRepository' => ['privates', 'App\\Repository\\AlumnoRepository', 'getAlumnoRepositoryService', true],
            'carrerasRepository' => ['privates', 'App\\Repository\\CarrerasRepository', 'getCarrerasRepositoryService', true],
            'docenteRepository' => ['privates', 'App\\Repository\\DocenteRepository', 'getDocenteRepositoryService', true],
            'personaRepository' => ['privates', 'App\\Repository\\PersonaRepository', 'getPersonaRepositoryService', true],
        ], [
            'alumnoRepository' => 'App\\Repository\\AlumnoRepository',
            'carrerasRepository' => 'App\\Repository\\CarrerasRepository',
            'docenteRepository' => 'App\\Repository\\DocenteRepository',
            'personaRepository' => 'App\\Repository\\PersonaRepository',
        ]);
    }
}
