<?php

namespace Container8Un2Ui4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XgoTMxUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XgoTMxU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XgoTMxU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cursadaDocenteRepository' => ['privates', 'App\\Repository\\CursadaDocenteRepository', 'getCursadaDocenteRepositoryService', true],
            'cursoRepository' => ['privates', 'App\\Repository\\CursoRepository', 'getCursoRepositoryService', true],
            'notaRepository' => ['privates', 'App\\Repository\\NotaRepository', 'getNotaRepositoryService', true],
        ], [
            'cursadaDocenteRepository' => 'App\\Repository\\CursadaDocenteRepository',
            'cursoRepository' => 'App\\Repository\\CursoRepository',
            'notaRepository' => 'App\\Repository\\NotaRepository',
        ]);
    }
}
