<?php

<<<<<<< HEAD:var/cache/dev/Container8Un2Ui4/getHabilitante2Service.php
namespace Container8Un2Ui4;
=======
<<<<<<<< HEAD:var/cache/dev/ContainerZedAest/getHabilitante2Service.php
namespace ContainerZedAest;

========
namespace ContainerWxp6ynK;
>>>>>>>> 15004e1e441728d7bfb90a33f34e34e28484990f:var/cache/dev/ContainerWxp6ynK/getHabilitante2Service.php
>>>>>>> 9ff131dc3f1d539d565d1ea1bbe799cf5823e506:var/cache/dev/ContainerWxp6ynK/getHabilitante2Service.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHabilitante2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.zHcbPEg.App\Entity\Habilitante' shared service.
     *
     * @return \App\Entity\Habilitante
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.zHcbPEg": it references class "App\\Entity\\Habilitante" but no such service exists.');
    }
}
