<?php

<<<<<<< HEAD:var/cache/dev/Container8Un2Ui4/getTurnoService.php
namespace Container8Un2Ui4;
=======
<<<<<<<< HEAD:var/cache/dev/ContainerZedAest/getTurnoService.php
namespace ContainerZedAest;

========
namespace ContainerWxp6ynK;
>>>>>>>> 15004e1e441728d7bfb90a33f34e34e28484990f:var/cache/dev/ContainerWxp6ynK/getTurnoService.php
>>>>>>> 9ff131dc3f1d539d565d1ea1bbe799cf5823e506:var/cache/dev/ContainerWxp6ynK/getTurnoService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTurnoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator..ra8kI_.App\Entity\Turno' shared service.
     *
     * @return \App\Entity\Turno
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator..ra8kI_": it references class "App\\Entity\\Turno" but no such service exists.');
    }
}
