<?php

namespace ContainerRooPL5S;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XfoL88HService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xfoL88H' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xfoL88H'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'carrerasRepository' => ['privates', 'App\\Repository\\CarrerasRepository', 'getCarrerasRepositoryService', true],
            'cursoRepository' => ['privates', 'App\\Repository\\CursoRepository', 'getCursoRepositoryService', true],
        ], [
            'carrerasRepository' => 'App\\Repository\\CarrerasRepository',
            'cursoRepository' => 'App\\Repository\\CursoRepository',
        ]);
    }
}
