<?php

namespace ContainerRooPL5S;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UqsmDdTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uqsmDdT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uqsmDdT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'asistenciaRepository' => ['privates', 'App\\Repository\\AsistenciaRepository', 'getAsistenciaRepositoryService', true],
            'asistencium' => ['privates', '.errored..service_locator.uqsmDdT.App\\Entity\\Asistencia', NULL, 'Cannot autowire service ".service_locator.uqsmDdT": it references class "App\\Entity\\Asistencia" but no such service exists.'],
        ], [
            'asistenciaRepository' => 'App\\Repository\\AsistenciaRepository',
            'asistencium' => 'App\\Entity\\Asistencia',
        ]);
    }
}
