<?php

namespace ContainerL0RvE4q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_O_5VTa1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.O.5VTa1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.O.5VTa1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'alumnoRepository' => ['privates', 'App\\Repository\\AlumnoRepository', 'getAlumnoRepositoryService', true],
            'inscripcionFinalRepository' => ['privates', 'App\\Repository\\InscripcionFinalRepository', 'getInscripcionFinalRepositoryService', true],
        ], [
            'alumnoRepository' => 'App\\Repository\\AlumnoRepository',
            'inscripcionFinalRepository' => 'App\\Repository\\InscripcionFinalRepository',
        ]);
    }
}
