<?php

namespace ContainerL0RvE4q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Lj6XXojService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lj6XXoj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lj6XXoj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'carrera' => ['privates', '.errored..service_locator.lj6XXoj.App\\Entity\\Carreras', NULL, 'Cannot autowire service ".service_locator.lj6XXoj": it references class "App\\Entity\\Carreras" but no such service exists.'],
        ], [
            'carrera' => 'App\\Entity\\Carreras',
        ]);
    }
}
