<?php

namespace ContainerL0RvE4q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DBXl6cRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dBXl6cR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dBXl6cR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'calendarioRepo' => ['privates', 'App\\Repository\\CalendarioClaseRepository', 'getCalendarioClaseRepositoryService', true],
            'cursadaRepo' => ['privates', 'App\\Repository\\CursadaRepository', 'getCursadaRepositoryService', true],
            'cursoRepo' => ['privates', 'App\\Repository\\CursoRepository', 'getCursoRepositoryService', true],
        ], [
            'calendarioRepo' => 'App\\Repository\\CalendarioClaseRepository',
            'cursadaRepo' => 'App\\Repository\\CursadaRepository',
            'cursoRepo' => 'App\\Repository\\CursoRepository',
        ]);
    }
}
