<?php

namespace ContainerL0RvE4q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHorario2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.esjls9Y.App\Entity\Horario' shared service.
     *
     * @return \App\Entity\Horario
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.esjls9Y": it references class "App\\Entity\\Horario" but no such service exists.');
    }
}
