<?php

namespace ContainerIsKKmRZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UH9HhJuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UH9HhJu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UH9HhJu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'telefono' => ['privates', '.errored..service_locator.UH9HhJu.App\\Entity\\Telefono', NULL, 'Cannot autowire service ".service_locator.UH9HhJu": it references class "App\\Entity\\Telefono" but no such service exists.'],
        ], [
            'telefono' => 'App\\Entity\\Telefono',
        ]);
    }
}
