<?php

namespace ContainerIsKKmRZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4EHAhEcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4EHAhEc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4EHAhEc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'examenAlumnoRepository' => ['privates', 'App\\Repository\\ExamenAlumnoRepository', 'getExamenAlumnoRepositoryService', true],
            'examenFinal' => ['privates', '.errored..service_locator.4EHAhEc.App\\Entity\\ExamenFinal', NULL, 'Cannot autowire service ".service_locator.4EHAhEc": it references class "App\\Entity\\ExamenFinal" but no such service exists.'],
            'examenFinalRepository' => ['privates', 'App\\Repository\\ExamenFinalRepository', 'getExamenFinalRepositoryService', true],
        ], [
            'examenAlumnoRepository' => 'App\\Repository\\ExamenAlumnoRepository',
            'examenFinal' => 'App\\Entity\\ExamenFinal',
            'examenFinalRepository' => 'App\\Repository\\ExamenFinalRepository',
        ]);
    }
}
