<?php

<<<<<<<< HEAD:var/cache/dev/ContainerLxcwixx/get_ServiceLocator_1Qpv22Service.php
namespace ContainerLxcwixx;
========
namespace ContainerPx58x1J;
>>>>>>>> 14397690d78e5c4d99a6bfbe6f9721f530690f30:var/cache/dev/ContainerPx58x1J/get_ServiceLocator_1Qpv22Service.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1Qpv22Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1_Qpv22' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1_Qpv22'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'instituto' => ['privates', '.errored..service_locator.1_Qpv22.App\\Entity\\Instituto', NULL, 'Cannot autowire service ".service_locator.1_Qpv22": it references class "App\\Entity\\Instituto" but no such service exists.'],
        ], [
            'instituto' => 'App\\Entity\\Instituto',
        ]);
    }
}
