<?php

<<<<<<<< HEAD:var/cache/dev/ContainerLxcwixx/get_ServiceLocator_HeTDv4Service.php
namespace ContainerLxcwixx;
========
namespace ContainerPx58x1J;
>>>>>>>> 14397690d78e5c4d99a6bfbe6f9721f530690f30:var/cache/dev/ContainerPx58x1J/get_ServiceLocator_HeTDv4Service.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HeTDv4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.He_tDv4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.He_tDv4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cursadaDocente' => ['privates', '.errored..service_locator.He_tDv4.App\\Entity\\CursadaDocente', NULL, 'Cannot autowire service ".service_locator.He_tDv4": it references class "App\\Entity\\CursadaDocente" but no such service exists.'],
            'cursadaDocenteRepository' => ['privates', 'App\\Repository\\CursadaDocenteRepository', 'getCursadaDocenteRepositoryService', true],
        ], [
            'cursadaDocente' => 'App\\Entity\\CursadaDocente',
            'cursadaDocenteRepository' => 'App\\Repository\\CursadaDocenteRepository',
        ]);
    }
}
