<?php

<<<<<<<< HEAD:var/cache/dev/ContainerLxcwixx/get_ServiceLocator_RaaoeKjService.php
namespace ContainerLxcwixx;
========
namespace ContainerPx58x1J;
>>>>>>>> 14397690d78e5c4d99a6bfbe6f9721f530690f30:var/cache/dev/ContainerPx58x1J/get_ServiceLocator_RaaoeKjService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RaaoeKjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.raaoeKj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.raaoeKj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'asignatura' => ['privates', '.errored..service_locator.raaoeKj.App\\Entity\\Asignatura', NULL, 'Cannot autowire service ".service_locator.raaoeKj": it references class "App\\Entity\\Asignatura" but no such service exists.'],
            'asignaturaRepository' => ['privates', 'App\\Repository\\AsignaturaRepository', 'getAsignaturaRepositoryService', true],
            'tecnicaturaRepository' => ['privates', 'App\\Repository\\TecnicaturaRepository', 'getTecnicaturaRepositoryService', true],
        ], [
            'asignatura' => 'App\\Entity\\Asignatura',
            'asignaturaRepository' => 'App\\Repository\\AsignaturaRepository',
            'tecnicaturaRepository' => 'App\\Repository\\TecnicaturaRepository',
        ]);
    }
}
