<?php

<<<<<<<< HEAD:var/cache/dev/ContainerLxcwixx/get_ServiceLocator_8U7NquService.php
namespace ContainerLxcwixx;
========
namespace ContainerPx58x1J;
>>>>>>>> 14397690d78e5c4d99a6bfbe6f9721f530690f30:var/cache/dev/ContainerPx58x1J/get_ServiceLocator_8U7NquService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8U7NquService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8_u7Nqu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8_u7Nqu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'carrerasRepository' => ['privates', 'App\\Repository\\CarrerasRepository', 'getCarrerasRepositoryService', true],
            'cursoRepository' => ['privates', 'App\\Repository\\CursoRepository', 'getCursoRepositoryService', true],
        ], [
            'carrerasRepository' => 'App\\Repository\\CarrerasRepository',
            'cursoRepository' => 'App\\Repository\\CursoRepository',
        ]);
    }
}
