<?php

<<<<<<<< HEAD:var/cache/dev/ContainerLxcwixx/get_ServiceLocator_TJkIAIService.php
namespace ContainerLxcwixx;
========
namespace ContainerPx58x1J;
>>>>>>>> 14397690d78e5c4d99a6bfbe6f9721f530690f30:var/cache/dev/ContainerPx58x1J/get_ServiceLocator_TJkIAIService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TJkIAIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TJkIAI_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TJkIAI_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'pai' => ['privates', '.errored..service_locator.TJkIAI_.App\\Entity\\Pais', NULL, 'Cannot autowire service ".service_locator.TJkIAI_": it references class "App\\Entity\\Pais" but no such service exists.'],
        ], [
            'pai' => 'App\\Entity\\Pais',
        ]);
    }
}
