<?php

<<<<<<<< HEAD:var/cache/dev/ContainerLxcwixx/get_ServiceLocator_2m7_IhxService.php
namespace ContainerLxcwixx;
========
namespace ContainerPx58x1J;
>>>>>>>> 14397690d78e5c4d99a6bfbe6f9721f530690f30:var/cache/dev/ContainerPx58x1J/get_ServiceLocator_2m7_IhxService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2m7_IhxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2m7.ihx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2m7.ihx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'modalidadRepository' => ['privates', 'App\\Repository\\ModalidadRepository', 'getModalidadRepositoryService', true],
        ], [
            'modalidadRepository' => 'App\\Repository\\ModalidadRepository',
        ]);
    }
}
