<?php

namespace ContainerPx58x1J;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IdHXkW9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.idHXkW9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.idHXkW9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'carreras' => ['privates', '.errored..service_locator.idHXkW9.App\\Entity\\Carreras', NULL, 'Cannot autowire service ".service_locator.idHXkW9": it references class "App\\Entity\\Carreras" but no such service exists.'],
            'carrerasRepository' => ['privates', 'App\\Repository\\CarrerasRepository', 'getCarrerasRepositoryService', true],
        ], [
            'carreras' => 'App\\Entity\\Carreras',
            'carrerasRepository' => 'App\\Repository\\CarrerasRepository',
        ]);
    }
}
