<?php

<<<<<<<< HEAD:var/cache/dev/ContainerLxcwixx/get_ServiceLocator_Lv5K54wService.php
namespace ContainerLxcwixx;
========
namespace ContainerPx58x1J;
>>>>>>>> 14397690d78e5c4d99a6bfbe6f9721f530690f30:var/cache/dev/ContainerPx58x1J/get_ServiceLocator_Lv5K54wService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Lv5K54wService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Lv5K54w' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Lv5K54w'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'curso' => ['privates', '.errored..service_locator.Lv5K54w.App\\Entity\\Curso', NULL, 'Cannot autowire service ".service_locator.Lv5K54w": it references class "App\\Entity\\Curso" but no such service exists.'],
            'cursoRepository' => ['privates', 'App\\Repository\\CursoRepository', 'getCursoRepositoryService', true],
        ], [
            'curso' => 'App\\Entity\\Curso',
            'cursoRepository' => 'App\\Repository\\CursoRepository',
        ]);
    }
}
