<?php

<<<<<<<< HEAD:var/cache/dev/ContainerLxcwixx/get_ServiceLocator_CJRo3qTService.php
namespace ContainerLxcwixx;
========
namespace ContainerPx58x1J;
>>>>>>>> 14397690d78e5c4d99a6bfbe6f9721f530690f30:var/cache/dev/ContainerPx58x1J/get_ServiceLocator_CJRo3qTService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CJRo3qTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cJRo3qT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cJRo3qT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'examenAlumno' => ['privates', '.errored..service_locator.cJRo3qT.App\\Entity\\ExamenAlumno', NULL, 'Cannot autowire service ".service_locator.cJRo3qT": it references class "App\\Entity\\ExamenAlumno" but no such service exists.'],
        ], [
            'examenAlumno' => 'App\\Entity\\ExamenAlumno',
        ]);
    }
}
