<?php

<<<<<<<< HEAD:var/cache/dev/ContainerZYHxHcm/get_ServiceLocator__JJzQmVService.php
namespace ContainerZYHxHcm;

========
namespace ContainerPx58x1J;
>>>>>>>> dbb35f2e0ed046077df855ec631d238ddedf5cd8:var/cache/dev/ContainerPx58x1J/get_ServiceLocator_RaaoeKjService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__JJzQmVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..JJzQmV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..JJzQmV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'asignatura' => ['privates', '.errored..service_locator..JJzQmV.App\\Entity\\Asignatura', NULL, 'Cannot autowire service ".service_locator..JJzQmV": it references class "App\\Entity\\Asignatura" but no such service exists.'],
            'asignaturaRepository' => ['privates', 'App\\Repository\\AsignaturaRepository', 'getAsignaturaRepositoryService', true],
            'tecnicaturaRepository' => ['privates', 'App\\Repository\\TecnicaturaRepository', 'getTecnicaturaRepositoryService', true],
        ], [
            'asignatura' => 'App\\Entity\\Asignatura',
            'asignaturaRepository' => 'App\\Repository\\AsignaturaRepository',
            'tecnicaturaRepository' => 'App\\Repository\\TecnicaturaRepository',
        ]);
    }
}
