<?php

<<<<<<<< HEAD:var/cache/dev/ContainerLxcwixx/get_ServiceLocator_BdWCJiqService.php
namespace ContainerLxcwixx;
========
namespace ContainerPx58x1J;
>>>>>>>> 14397690d78e5c4d99a6bfbe6f9721f530690f30:var/cache/dev/ContainerPx58x1J/get_ServiceLocator_BdWCJiqService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BdWCJiqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BdWCJiq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BdWCJiq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'carrera' => ['privates', '.errored..service_locator.BdWCJiq.App\\Entity\\Carreras', NULL, 'Cannot autowire service ".service_locator.BdWCJiq": it references class "App\\Entity\\Carreras" but no such service exists.'],
            'carrerasRepository' => ['privates', 'App\\Repository\\CarrerasRepository', 'getCarrerasRepositoryService', true],
        ], [
            'carrera' => 'App\\Entity\\Carreras',
            'carrerasRepository' => 'App\\Repository\\CarrerasRepository',
        ]);
    }
}
