<?php

<<<<<<<< HEAD:var/cache/dev/ContainerLxcwixx/get_ServiceLocator_IrC2JnmService.php
namespace ContainerLxcwixx;
========
namespace ContainerPx58x1J;
>>>>>>>> 14397690d78e5c4d99a6bfbe6f9721f530690f30:var/cache/dev/ContainerPx58x1J/get_ServiceLocator_IrC2JnmService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IrC2JnmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.irC2Jnm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.irC2Jnm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'calendarioClaseRepository' => ['privates', 'App\\Repository\\CalendarioClaseRepository', 'getCalendarioClaseRepositoryService', true],
        ], [
            'calendarioClaseRepository' => 'App\\Repository\\CalendarioClaseRepository',
        ]);
    }
}
