<?php

<<<<<<<< HEAD:var/cache/dev/ContainerZYHxHcm/get_ServiceLocator_Dy1U4_Service.php
namespace ContainerZYHxHcm;

========
namespace ContainerPx58x1J;
>>>>>>>> dbb35f2e0ed046077df855ec631d238ddedf5cd8:var/cache/dev/ContainerPx58x1J/get_ServiceLocator_OuOW6lSService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Dy1U4_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._Dy1U4.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._Dy1U4.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repo' => ['privates', 'App\\Repository\\CalendarioClaseRepository', 'getCalendarioClaseRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\CalendarioClaseRepository',
        ]);
    }
}
