<?php

<<<<<<<< HEAD:var/cache/dev/ContainerLxcwixx/get_ServiceLocator_BAD3la7Service.php
namespace ContainerLxcwixx;
========
namespace ContainerPx58x1J;
>>>>>>>> 14397690d78e5c4d99a6bfbe6f9721f530690f30:var/cache/dev/ContainerPx58x1J/get_ServiceLocator_BAD3la7Service.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BAD3la7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bAD3la7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bAD3la7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'turno' => ['privates', '.errored..service_locator.bAD3la7.App\\Entity\\Turno', NULL, 'Cannot autowire service ".service_locator.bAD3la7": it references class "App\\Entity\\Turno" but no such service exists.'],
        ], [
            'turno' => 'App\\Entity\\Turno',
        ]);
    }
}
