<?php

namespace ContainerPx58x1J;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_29s7hJ1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.29s7hJ1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.29s7hJ1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'examenAlumnoRepository' => ['privates', 'App\\Repository\\ExamenAlumnoRepository', 'getExamenAlumnoRepositoryService', true],
            'examenFinalRepository' => ['privates', 'App\\Repository\\ExamenFinalRepository', 'getExamenFinalRepositoryService', true],
            'inscripcionFinalRepository' => ['privates', 'App\\Repository\\InscripcionFinalRepository', 'getInscripcionFinalRepositoryService', true],
        ], [
            'examenAlumnoRepository' => 'App\\Repository\\ExamenAlumnoRepository',
            'examenFinalRepository' => 'App\\Repository\\ExamenFinalRepository',
            'inscripcionFinalRepository' => 'App\\Repository\\InscripcionFinalRepository',
        ]);
    }
}
