<?php

<<<<<<<< HEAD:var/cache/dev/ContainerLxcwixx/get_ServiceLocator_OmZi5k_Service.php
namespace ContainerLxcwixx;
========
namespace ContainerPx58x1J;
>>>>>>>> 14397690d78e5c4d99a6bfbe6f9721f530690f30:var/cache/dev/ContainerPx58x1J/get_ServiceLocator_OmZi5k_Service.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OmZi5k_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.omZi5k.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.omZi5k.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'alumnoRepository' => ['privates', 'App\\Repository\\AlumnoRepository', 'getAlumnoRepositoryService', true],
            'carrerasRepository' => ['privates', 'App\\Repository\\CarrerasRepository', 'getCarrerasRepositoryService', true],
            'institutoRepository' => ['privates', 'App\\Repository\\InstitutoRepository', 'getInstitutoRepositoryService', true],
            'personaRepository' => ['privates', 'App\\Repository\\PersonaRepository', 'getPersonaRepositoryService', true],
        ], [
            'alumnoRepository' => 'App\\Repository\\AlumnoRepository',
            'carrerasRepository' => 'App\\Repository\\CarrerasRepository',
            'institutoRepository' => 'App\\Repository\\InstitutoRepository',
            'personaRepository' => 'App\\Repository\\PersonaRepository',
        ]);
    }
}
