<?php

<<<<<<<< HEAD:var/cache/dev/ContainerLxcwixx/get_ServiceLocator_DQzUaDuService.php
namespace ContainerLxcwixx;
========
namespace ContainerPx58x1J;
>>>>>>>> 14397690d78e5c4d99a6bfbe6f9721f530690f30:var/cache/dev/ContainerPx58x1J/get_ServiceLocator_DQzUaDuService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DQzUaDuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dQzUaDu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dQzUaDu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'correlativa' => ['privates', '.errored..service_locator.dQzUaDu.App\\Entity\\Correlativa', NULL, 'Cannot autowire service ".service_locator.dQzUaDu": it references class "App\\Entity\\Correlativa" but no such service exists.'],
        ], [
            'correlativa' => 'App\\Entity\\Correlativa',
        ]);
    }
}
