<?php

<<<<<<<< HEAD:var/cache/dev/ContainerLxcwixx/get_ServiceLocator_BIPZ3W7Service.php
namespace ContainerLxcwixx;
========
namespace ContainerPx58x1J;
>>>>>>>> 14397690d78e5c4d99a6bfbe6f9721f530690f30:var/cache/dev/ContainerPx58x1J/get_ServiceLocator_BIPZ3W7Service.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BIPZ3W7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bIPZ3W7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bIPZ3W7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'horario' => ['privates', '.errored..service_locator.bIPZ3W7.App\\Entity\\Horario', NULL, 'Cannot autowire service ".service_locator.bIPZ3W7": it references class "App\\Entity\\Horario" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'horario' => 'App\\Entity\\Horario',
        ]);
    }
}
