<?php

<<<<<<<< HEAD:var/cache/dev/ContainerLxcwixx/get_ServiceLocator_ME2wygXService.php
namespace ContainerLxcwixx;
========
namespace ContainerPx58x1J;
>>>>>>>> 14397690d78e5c4d99a6bfbe6f9721f530690f30:var/cache/dev/ContainerPx58x1J/get_ServiceLocator_ME2wygXService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ME2wygXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mE2wygX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mE2wygX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'tecnicatura' => ['privates', '.errored..service_locator.mE2wygX.App\\Entity\\Tecnicatura', NULL, 'Cannot autowire service ".service_locator.mE2wygX": it references class "App\\Entity\\Tecnicatura" but no such service exists.'],
            'tecnicaturaRepository' => ['privates', 'App\\Repository\\TecnicaturaRepository', 'getTecnicaturaRepositoryService', true],
        ], [
            'tecnicatura' => 'App\\Entity\\Tecnicatura',
            'tecnicaturaRepository' => 'App\\Repository\\TecnicaturaRepository',
        ]);
    }
}
