<?php

<<<<<<<< HEAD:var/cache/dev/ContainerLxcwixx/get_ServiceLocator_BttjbPlService.php
namespace ContainerLxcwixx;
========
namespace ContainerPx58x1J;
>>>>>>>> 14397690d78e5c4d99a6bfbe6f9721f530690f30:var/cache/dev/ContainerPx58x1J/get_ServiceLocator_BttjbPlService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BttjbPlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bttjbPl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bttjbPl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'modalidad' => ['privates', '.errored..service_locator.bttjbPl.App\\Entity\\Modalidad', NULL, 'Cannot autowire service ".service_locator.bttjbPl": it references class "App\\Entity\\Modalidad" but no such service exists.'],
            'modalidadRepository' => ['privates', 'App\\Repository\\ModalidadRepository', 'getModalidadRepositoryService', true],
        ], [
            'modalidad' => 'App\\Entity\\Modalidad',
            'modalidadRepository' => 'App\\Repository\\ModalidadRepository',
        ]);
    }
}
