<?php

<<<<<<<< HEAD:var/cache/dev/ContainerZYHxHcm/get_ServiceLocator_V1z4OxoService.php
namespace ContainerZYHxHcm;

========
namespace ContainerPx58x1J;
>>>>>>>> dbb35f2e0ed046077df855ec631d238ddedf5cd8:var/cache/dev/ContainerPx58x1J/get_ServiceLocator_M0J981lService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_V1z4OxoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.V1z4Oxo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.V1z4Oxo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'asistenciaRepository' => ['privates', 'App\\Repository\\AsistenciaRepository', 'getAsistenciaRepositoryService', true],
        ], [
            'asistenciaRepository' => 'App\\Repository\\AsistenciaRepository',
        ]);
    }
}
