<?php

<<<<<<<< HEAD:var/cache/dev/ContainerLxcwixx/get_ServiceLocator_6BT3nBgService.php
namespace ContainerLxcwixx;
========
namespace ContainerPx58x1J;
>>>>>>>> 14397690d78e5c4d99a6bfbe6f9721f530690f30:var/cache/dev/ContainerPx58x1J/get_ServiceLocator_6BT3nBgService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6BT3nBgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6BT3nBg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6BT3nBg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'asistencium' => ['privates', '.errored..service_locator.6BT3nBg.App\\Entity\\Asistencia', NULL, 'Cannot autowire service ".service_locator.6BT3nBg": it references class "App\\Entity\\Asistencia" but no such service exists.'],
        ], [
            'asistencium' => 'App\\Entity\\Asistencia',
        ]);
    }
}
