<?php

<<<<<<<< HEAD:var/cache/dev/ContainerZYHxHcm/get_ServiceLocator_Q8TnVXuService.php
namespace ContainerZYHxHcm;

========
namespace ContainerPx58x1J;
>>>>>>>> dbb35f2e0ed046077df855ec631d238ddedf5cd8:var/cache/dev/ContainerPx58x1J/get_ServiceLocator_LiLgd1_Service.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Q8TnVXuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.q8TnVXu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.q8TnVXu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'titulo' => ['privates', '.errored..service_locator.q8TnVXu.App\\Entity\\Titulo', NULL, 'Cannot autowire service ".service_locator.q8TnVXu": it references class "App\\Entity\\Titulo" but no such service exists.'],
        ], [
            'titulo' => 'App\\Entity\\Titulo',
        ]);
    }
}
