<?php

namespace ContainerPx58x1J;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EdV3fEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EdV3fE_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EdV3fE_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'rol' => ['privates', '.errored..service_locator.EdV3fE_.App\\Entity\\Rol', NULL, 'Cannot autowire service ".service_locator.EdV3fE_": it references class "App\\Entity\\Rol" but no such service exists.'],
        ], [
            'rol' => 'App\\Entity\\Rol',
        ]);
    }
}
