<?php

<<<<<<<< HEAD:var/cache/dev/ContainerLxcwixx/get_ServiceLocator_7MymQPJService.php
namespace ContainerLxcwixx;
========
namespace ContainerPx58x1J;
>>>>>>>> 14397690d78e5c4d99a6bfbe6f9721f530690f30:var/cache/dev/ContainerPx58x1J/get_ServiceLocator_7MymQPJService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7MymQPJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7MymQPJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7MymQPJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'alumno' => ['privates', '.errored..service_locator.7MymQPJ.App\\Entity\\Alumno', NULL, 'Cannot autowire service ".service_locator.7MymQPJ": it references class "App\\Entity\\Alumno" but no such service exists.'],
            'alumnoRepository' => ['privates', 'App\\Repository\\AlumnoRepository', 'getAlumnoRepositoryService', true],
        ], [
            'alumno' => 'App\\Entity\\Alumno',
            'alumnoRepository' => 'App\\Repository\\AlumnoRepository',
        ]);
    }
}
