<?php

<<<<<<<< HEAD:var/cache/dev/ContainerZYHxHcm/getAsignaturaService.php
namespace ContainerZYHxHcm;

========
namespace ContainerPx58x1J;
>>>>>>>> dbb35f2e0ed046077df855ec631d238ddedf5cd8:var/cache/dev/ContainerPx58x1J/getAsignaturaService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAsignaturaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator..JJzQmV.App\Entity\Asignatura' shared service.
     *
     * @return \App\Entity\Asignatura
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator..JJzQmV": it references class "App\\Entity\\Asignatura" but no such service exists.');
    }
}
