<?php

<<<<<<<< HEAD:var/cache/dev/ContainerZYHxHcm/getAlumno2Service.php
namespace ContainerZYHxHcm;

========
namespace ContainerPx58x1J;
>>>>>>>> dbb35f2e0ed046077df855ec631d238ddedf5cd8:var/cache/dev/ContainerPx58x1J/getAlumno2Service.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAlumno2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.hFQFq_g.App\Entity\Alumno' shared service.
     *
     * @return \App\Entity\Alumno
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.hFQFq_g": it references class "App\\Entity\\Alumno" but no such service exists.');
    }
}
