<?php

<<<<<<<< HEAD:var/cache/dev/ContainerLxcwixx/getAlumnoService.php
namespace ContainerLxcwixx;
========
namespace ContainerPx58x1J;
>>>>>>>> 14397690d78e5c4d99a6bfbe6f9721f530690f30:var/cache/dev/ContainerPx58x1J/getAlumnoService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAlumnoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.6sNqD9k.App\Entity\Alumno' shared service.
     *
     * @return \App\Entity\Alumno
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.6sNqD9k": it references class "App\\Entity\\Alumno" but no such service exists.');
    }
}
