<?php

<<<<<<<< HEAD:var/cache/dev/ContainerLxcwixx/getCursada2Service.php
namespace ContainerLxcwixx;
========
namespace ContainerPx58x1J;
>>>>>>>> 14397690d78e5c4d99a6bfbe6f9721f530690f30:var/cache/dev/ContainerPx58x1J/getCursada2Service.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCursada2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.u53w2.o.App\Entity\Cursada' shared service.
     *
     * @return \App\Entity\Cursada
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.u53w2.o": it references class "App\\Entity\\Cursada" but no such service exists.');
    }
}
