<?php

<<<<<<<< HEAD:var/cache/dev/ContainerZYHxHcm/getCursadaDocenteService.php
namespace ContainerZYHxHcm;

========
namespace ContainerPx58x1J;
>>>>>>>> dbb35f2e0ed046077df855ec631d238ddedf5cd8:var/cache/dev/ContainerPx58x1J/getCursadaDocenteService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCursadaDocenteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.dJZg4WQ.App\Entity\CursadaDocente' shared service.
     *
     * @return \App\Entity\CursadaDocente
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.dJZg4WQ": it references class "App\\Entity\\CursadaDocente" but no such service exists.');
    }
}
