<?php

<<<<<<<< HEAD:var/cache/dev/ContainerZYHxHcm/getCursoService.php
namespace ContainerZYHxHcm;

========
namespace ContainerPx58x1J;
>>>>>>>> dbb35f2e0ed046077df855ec631d238ddedf5cd8:var/cache/dev/ContainerPx58x1J/getCursoService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCursoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.FPVNRCt.App\Entity\Curso' shared service.
     *
     * @return \App\Entity\Curso
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.FPVNRCt": it references class "App\\Entity\\Curso" but no such service exists.');
    }
}
