<?php

<<<<<<<< HEAD:var/cache/dev/ContainerLxcwixx/getComisionService.php
namespace ContainerLxcwixx;
========
namespace ContainerPx58x1J;
>>>>>>>> 14397690d78e5c4d99a6bfbe6f9721f530690f30:var/cache/dev/ContainerPx58x1J/getComisionService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getComisionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator..A3Dw1B.App\Entity\Comision' shared service.
     *
     * @return \App\Entity\Comision
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator..A3Dw1B": it references class "App\\Entity\\Comision" but no such service exists.');
    }
}
