<?php

<<<<<<<< HEAD:var/cache/dev/ContainerZYHxHcm/getComisionService.php
namespace ContainerZYHxHcm;

========
namespace ContainerPx58x1J;
>>>>>>>> dbb35f2e0ed046077df855ec631d238ddedf5cd8:var/cache/dev/ContainerPx58x1J/getComisionService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getComisionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.5zZPUXR.App\Entity\Comision' shared service.
     *
     * @return \App\Entity\Comision
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.5zZPUXR": it references class "App\\Entity\\Comision" but no such service exists.');
    }
}
