<?php

<<<<<<<< HEAD:var/cache/dev/ContainerLxcwixx/getEmailCoincideConPersonaValidatorService.php
namespace ContainerLxcwixx;
========
namespace ContainerPx58x1J;
>>>>>>>> 14397690d78e5c4d99a6bfbe6f9721f530690f30:var/cache/dev/ContainerPx58x1J/getEmailCoincideConPersonaValidatorService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailCoincideConPersonaValidatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Validator\EmailCoincideConPersonaValidator' shared autowired service.
     *
     * @return \App\Validator\EmailCoincideConPersonaValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'validator'.\DIRECTORY_SEPARATOR.'ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'validator'.\DIRECTORY_SEPARATOR.'ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Validator'.\DIRECTORY_SEPARATOR.'EmailCoincideConPersonaValidator.php';

        return $container->privates['App\\Validator\\EmailCoincideConPersonaValidator'] = new \App\Validator\EmailCoincideConPersonaValidator();
    }
}
