<?php

<<<<<<<< HEAD:var/cache/dev/ContainerZYHxHcm/getExamenFinalService.php
namespace ContainerZYHxHcm;

========
namespace ContainerPx58x1J;
>>>>>>>> dbb35f2e0ed046077df855ec631d238ddedf5cd8:var/cache/dev/ContainerPx58x1J/getExamenFinalService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExamenFinalService extends App_KernelDevDebugContainer
{
    /**
<<<<<<<< HEAD:var/cache/dev/ContainerZYHxHcm/getExamenFinalService.php
     * Gets the private '.errored..service_locator.V8mJv2f.App\Entity\ExamenFinal' shared service.
========
     * Gets the private '.errored..service_locator.4EHAhEc.App\Entity\ExamenFinal' shared service.
>>>>>>>> dbb35f2e0ed046077df855ec631d238ddedf5cd8:var/cache/dev/ContainerPx58x1J/getExamenFinalService.php
     *
     * @return \App\Entity\ExamenFinal
     */
    public static function do($container, $lazyLoad = true)
    {
<<<<<<<< HEAD:var/cache/dev/ContainerZYHxHcm/getExamenFinalService.php
        $container->throw('Cannot autowire service ".service_locator.V8mJv2f": it references class "App\\Entity\\ExamenFinal" but no such service exists.');
========
        $container->throw('Cannot autowire service ".service_locator.4EHAhEc": it references class "App\\Entity\\ExamenFinal" but no such service exists.');
>>>>>>>> dbb35f2e0ed046077df855ec631d238ddedf5cd8:var/cache/dev/ContainerPx58x1J/getExamenFinalService.php
    }
}
