<?php

<<<<<<<< HEAD:var/cache/dev/ContainerZYHxHcm/getHabilitanteService.php
namespace ContainerZYHxHcm;

========
namespace ContainerPx58x1J;
>>>>>>>> dbb35f2e0ed046077df855ec631d238ddedf5cd8:var/cache/dev/ContainerPx58x1J/getHabilitanteService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHabilitanteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Yv4Ghdl.App\Entity\Habilitante' shared service.
     *
     * @return \App\Entity\Habilitante
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Yv4Ghdl": it references class "App\\Entity\\Habilitante" but no such service exists.');
    }
}
