<?php

<<<<<<<< HEAD:var/cache/dev/ContainerZYHxHcm/getInstitutoService.php
namespace ContainerZYHxHcm;

========
namespace ContainerPx58x1J;
>>>>>>>> dbb35f2e0ed046077df855ec631d238ddedf5cd8:var/cache/dev/ContainerPx58x1J/getInstitutoService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInstitutoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.LF4OuHN.App\Entity\Instituto' shared service.
     *
     * @return \App\Entity\Instituto
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.LF4OuHN": it references class "App\\Entity\\Instituto" but no such service exists.');
    }
}
