<?php

<<<<<<<< HEAD:var/cache/dev/ContainerLxcwixx/getInscripcionFinalService.php
namespace ContainerLxcwixx;
========
namespace ContainerPx58x1J;
>>>>>>>> 14397690d78e5c4d99a6bfbe6f9721f530690f30:var/cache/dev/ContainerPx58x1J/getInscripcionFinalService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInscripcionFinalService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.WW5KjXA.App\Entity\InscripcionFinal' shared service.
     *
     * @return \App\Entity\InscripcionFinal
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.WW5KjXA": it references class "App\\Entity\\InscripcionFinal" but no such service exists.');
    }
}
