<?php

<<<<<<<< HEAD:var/cache/dev/ContainerLxcwixx/getLocalidadService.php
namespace ContainerLxcwixx;
========
namespace ContainerPx58x1J;
>>>>>>>> 14397690d78e5c4d99a6bfbe6f9721f530690f30:var/cache/dev/ContainerPx58x1J/getLocalidadService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLocalidadService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.98vJ9rN.App\Entity\Localidad' shared service.
     *
     * @return \App\Entity\Localidad
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.98vJ9rN": it references class "App\\Entity\\Localidad" but no such service exists.');
    }
}
