<?php

<<<<<<<< HEAD:var/cache/dev/ContainerZYHxHcm/getNota2Service.php
namespace ContainerZYHxHcm;

========
namespace ContainerPx58x1J;
>>>>>>>> dbb35f2e0ed046077df855ec631d238ddedf5cd8:var/cache/dev/ContainerPx58x1J/getNota2Service.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNota2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.FEhGlnP.App\Entity\Nota' shared service.
     *
     * @return \App\Entity\Nota
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.FEhGlnP": it references class "App\\Entity\\Nota" but no such service exists.');
    }
}
