<?php

<<<<<<<< HEAD:var/cache/dev/ContainerLxcwixx/getNotaService.php
namespace ContainerLxcwixx;
========
namespace ContainerPx58x1J;
>>>>>>>> 14397690d78e5c4d99a6bfbe6f9721f530690f30:var/cache/dev/ContainerPx58x1J/getNotaService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator..RP8fEe.App\Entity\Nota' shared service.
     *
     * @return \App\Entity\Nota
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator..RP8fEe": it references class "App\\Entity\\Nota" but no such service exists.');
    }
}
