<?php

<<<<<<<< HEAD:var/cache/dev/ContainerZYHxHcm/getRegionService.php
namespace ContainerZYHxHcm;

========
namespace ContainerPx58x1J;
>>>>>>>> dbb35f2e0ed046077df855ec631d238ddedf5cd8:var/cache/dev/ContainerPx58x1J/getRegionService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.is9d6bI.App\Entity\Region' shared service.
     *
     * @return \App\Entity\Region
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.is9d6bI": it references class "App\\Entity\\Region" but no such service exists.');
    }
}
