<?php

<<<<<<<< HEAD:var/cache/dev/ContainerLxcwixx/getTelefono2Service.php
namespace ContainerLxcwixx;
========
namespace ContainerPx58x1J;
>>>>>>>> 14397690d78e5c4d99a6bfbe6f9721f530690f30:var/cache/dev/ContainerPx58x1J/getTelefono2Service.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTelefono2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.nFf2lw3.App\Entity\Telefono' shared service.
     *
     * @return \App\Entity\Telefono
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.nFf2lw3": it references class "App\\Entity\\Telefono" but no such service exists.');
    }
}
