<?php

<<<<<<<< HEAD:var/cache/dev/ContainerLxcwixx/getTecnicaturaService.php
namespace ContainerLxcwixx;
========
namespace ContainerPx58x1J;
>>>>>>>> 14397690d78e5c4d99a6bfbe6f9721f530690f30:var/cache/dev/ContainerPx58x1J/getTecnicaturaService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTecnicaturaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.dpFd_PZ.App\Entity\Tecnicatura' shared service.
     *
     * @return \App\Entity\Tecnicatura
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.dpFd_PZ": it references class "App\\Entity\\Tecnicatura" but no such service exists.');
    }
}
