<?php

<<<<<<<< HEAD:var/cache/dev/ContainerZYHxHcm/getUser3Service.php
namespace ContainerZYHxHcm;

========
namespace ContainerPx58x1J;
>>>>>>>> dbb35f2e0ed046077df855ec631d238ddedf5cd8:var/cache/dev/ContainerPx58x1J/getUser3Service.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUser3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.TNwhQMg.App\Entity\User' shared service.
     *
     * @return \App\Entity\User
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.TNwhQMg": it references class "App\\Entity\\User" but no such service exists.');
    }
}
