<?php

namespace ContainerRAM2H65;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VwfW7ARService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VwfW7AR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VwfW7AR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'calendarioClaseRepository' => ['privates', 'App\\Repository\\CalendarioClaseRepository', 'getCalendarioClaseRepositoryService', true],
            'cursadaRepository' => ['privates', 'App\\Repository\\CursadaRepository', 'getCursadaRepositoryService', true],
            'cursoRepository' => ['privates', 'App\\Repository\\CursoRepository', 'getCursoRepositoryService', true],
        ], [
            'calendarioClaseRepository' => 'App\\Repository\\CalendarioClaseRepository',
            'cursadaRepository' => 'App\\Repository\\CursadaRepository',
            'cursoRepository' => 'App\\Repository\\CursoRepository',
        ]);
    }
}
