<?php

namespace ContainerRAM2H65;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExamenAlumno2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.gceykvT.App\Entity\ExamenAlumno' shared service.
     *
     * @return \App\Entity\ExamenAlumno
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.gceykvT": it references class "App\\Entity\\ExamenAlumno" but no such service exists.');
    }
}
