<?php

namespace ContainerRAM2H65;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRolService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.EdV3fE_.App\Entity\Rol' shared service.
     *
     * @return \App\Entity\Rol
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.EdV3fE_": it references class "App\\Entity\\Rol" but no such service exists.');
    }
}
