<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerErybxW7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerErybxW7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerErybxW7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerErybxW7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerErybxW7\App_KernelDevDebugContainer([
    'container.build_hash' => 'ErybxW7',
    'container.build_id' => '46f3249f',
    'container.build_time' => 1750652295,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerErybxW7');
