<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVxFxMKO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVxFxMKO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVxFxMKO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVxFxMKO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVxFxMKO\App_KernelDevDebugContainer([
    'container.build_hash' => 'VxFxMKO',
    'container.build_id' => 'c6e5f3f3',
    'container.build_time' => 1751089281,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVxFxMKO');
