<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIsKKmRZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIsKKmRZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIsKKmRZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIsKKmRZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIsKKmRZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'IsKKmRZ',
    'container.build_id' => '8e30a0f9',
    'container.build_time' => 1749947808,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIsKKmRZ');
