<?php

namespace ContainerZedAest;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Bl3y0syService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Bl3y0sy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Bl3y0sy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cursadaRepository' => ['privates', 'App\\Repository\\CursadaRepository', 'getCursadaRepositoryService', true],
            'cursoRepository' => ['privates', 'App\\Repository\\CursoRepository', 'getCursoRepositoryService', true],
        ], [
            'cursadaRepository' => 'App\\Repository\\CursadaRepository',
            'cursoRepository' => 'App\\Repository\\CursoRepository',
        ]);
    }
}
