<?php

namespace ContainerWxp6ynK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DgvuIATService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dgvuIAT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dgvuIAT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'habilitante' => ['privates', '.errored..service_locator.dgvuIAT.App\\Entity\\Habilitante', NULL, 'Cannot autowire service ".service_locator.dgvuIAT": it references class "App\\Entity\\Habilitante" but no such service exists.'],
            'habilitanteRepository' => ['privates', 'App\\Repository\\HabilitanteRepository', 'getHabilitanteRepositoryService', true],
        ], [
            'habilitante' => 'App\\Entity\\Habilitante',
            'habilitanteRepository' => 'App\\Repository\\HabilitanteRepository',
        ]);
    }
}
