<?php

<<<<<<<< HEAD:var/cache/dev/ContainerZedAest/get_ServiceLocator_ZHcbPEgService.php
namespace ContainerZedAest;

========
namespace ContainerWxp6ynK;
>>>>>>>> 15004e1e441728d7bfb90a33f34e34e28484990f:var/cache/dev/ContainerWxp6ynK/get_ServiceLocator_DgvuIATService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZHcbPEgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zHcbPEg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zHcbPEg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'habilitante' => ['privates', '.errored..service_locator.zHcbPEg.App\\Entity\\Habilitante', NULL, 'Cannot autowire service ".service_locator.zHcbPEg": it references class "App\\Entity\\Habilitante" but no such service exists.'],
            'habilitanteRepository' => ['privates', 'App\\Repository\\HabilitanteRepository', 'getHabilitanteRepositoryService', true],
        ], [
            'habilitante' => 'App\\Entity\\Habilitante',
            'habilitanteRepository' => 'App\\Repository\\HabilitanteRepository',
        ]);
    }
}
