<?php

<<<<<<<< HEAD:var/cache/dev/ContainerZedAest/getCarreras3Service.php
namespace ContainerZedAest;

========
namespace ContainerWxp6ynK;
>>>>>>>> 15004e1e441728d7bfb90a33f34e34e28484990f:var/cache/dev/ContainerWxp6ynK/getCarreras3Service.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarreras3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.lj6XXoj.App\Entity\Carreras' shared service.
     *
     * @return \App\Entity\Carreras
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.lj6XXoj": it references class "App\\Entity\\Carreras" but no such service exists.');
    }
}
