<?php

<<<<<<<< HEAD:var/cache/dev/ContainerZedAest/getRevistaService.php
namespace ContainerZedAest;

========
namespace ContainerWxp6ynK;
>>>>>>>> 15004e1e441728d7bfb90a33f34e34e28484990f:var/cache/dev/ContainerWxp6ynK/getRevistaService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRevistaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.5fwZ1jo.App\Entity\Revista' shared service.
     *
     * @return \App\Entity\Revista
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.5fwZ1jo": it references class "App\\Entity\\Revista" but no such service exists.');
    }
}
