<?php

<<<<<<<< HEAD:var/cache/dev/ContainerZedAest/getRolService.php
namespace ContainerZedAest;

========
namespace ContainerWxp6ynK;
>>>>>>>> 15004e1e441728d7bfb90a33f34e34e28484990f:var/cache/dev/ContainerWxp6ynK/getRolService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRolService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.MFzlSFV.App\Entity\Rol' shared service.
     *
     * @return \App\Entity\Rol
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.MFzlSFV": it references class "App\\Entity\\Rol" but no such service exists.');
    }
}
