<?php

<<<<<<<< HEAD:var/cache/dev/ContainerZedAest/getTecnicaturaService.php
namespace ContainerZedAest;

========
namespace ContainerWxp6ynK;
>>>>>>>> 15004e1e441728d7bfb90a33f34e34e28484990f:var/cache/dev/ContainerWxp6ynK/getTecnicaturaService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTecnicaturaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator..0vGhcy.App\Entity\Tecnicatura' shared service.
     *
     * @return \App\Entity\Tecnicatura
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator..0vGhcy": it references class "App\\Entity\\Tecnicatura" but no such service exists.');
    }
}
